backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Accueil"
        name: "index"
        file: "index.html"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Contenu", name: "body", widget: "markdown"}
